# Docker image
# Build a Docker image to run, deploy, or push to a container registry.
# Add steps that use Docker Compose, tag images, push to a registry, run an image, and more:
# https://docs.microsoft.com/vsts/pipelines/languages/docker

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'cntkflaskwebapp:$(build.buildId)'

steps:
- script: |
    docker build -f Dockerfile -t $(dockerIdAcr).azurecr.io/$(imageName) .
    docker login -u $(dockerIdAcr) -p $pswd $(dockerIdAcr).azurecr.io
    docker push $(dockerIdAcr).azurecr.io/$(imageName)
  env:
    pswd: $(dockerPasswordAcr)
  displayName: 'Build and push Docker image to ARC'